"""Shared skip markers and constants for the topochange test suite.

Import these in individual test files:
    from tests.skip_markers import requires_pdal, requires_small_gicp, SYNTHETIC"""

import pytest


def _pdal_available() -> bool:
    # first check if the native PDAL module works
    try:
        import pdal  # noqa: F401
        return True
    except (ImportError, OSError):
        pass
    # fall back to checking the project's wrapper internals
    try:
        from topochange.pdal_wrapper import _NATIVE_PDAL_AVAILABLE, _CONDA_PDAL_AVAILABLE
        return _NATIVE_PDAL_AVAILABLE or _CONDA_PDAL_AVAILABLE
    except ImportError:
        return False


def _small_gicp_available() -> bool:
    try:
        import small_gicp  # noqa: F401
        return True
    except ImportError:
        return False


def _gdal_available() -> bool:
    try:
        from osgeo import gdal  # noqa: F401
        return True
    except ImportError:
        return False


HAS_PDAL = _pdal_available()
HAS_SMALL_GICP = _small_gicp_available()
HAS_GDAL = _gdal_available()

requires_pdal = pytest.mark.skipif(
    not HAS_PDAL, reason="PDAL is not installed"
)
requires_small_gicp = pytest.mark.skipif(
    not HAS_SMALL_GICP, reason="small_gicp is not installed"
)
requires_gdal = pytest.mark.skipif(
    not HAS_GDAL, reason="GDAL (osgeo) is not installed"
)

def _safe_num_threads() -> int:
    """Thread count that is safe to hand to small_gicp in this test suite.

    small_gicp and PDAL each bundle their own OpenMP runtime. On macOS, once
    both are loaded in one process, small_gicp's multithreaded preprocessing
    livelocks against PDAL's: the call never returns and never crashes, so a
    test run stalls indefinitely rather than failing. The package guards
    against this in ``topochange.alignment._default_num_threads`` (1 on macOS,
    multi-core elsewhere); any test that calls ``small_gicp`` directly has to
    follow the same policy or it hangs the run once a PDAL test has executed.

    Always use this constant in tests instead of a literal thread count.
    """
    try:
        from topochange.alignment import _default_num_threads
        return _default_num_threads()
    except Exception:
        return 1


SAFE_NUM_THREADS = _safe_num_threads()

# ground-truth values for the synthetic LAZ data generated by conftest.py
SYNTHETIC = dict(
    epsg=32610,
    n_points=50_000,
    x_offset=500_000.0,
    y_offset=4_000_000.0,
    x_extent=500.0,
    y_extent=500.0,
    z_base=1000.0,
    z_shift_compare=0.0,
    z_shift_reference=0.5,
)

